services:
  - type: web
    name: bplo-user-frontend
    env: static
    buildCommand: cd user && npm install && npm run build
    staticPublishPath: ./user/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: /
    autoDeploy: true
